nosql/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.nosql_list, name='nosql_list'),
    url(r'^(?P<datamodel_slug>[-\w]+)/$', views.nosql_list, name='nosql_list_by_datamodel'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.nosql_detail, name='nosql_detail'),

    # urls to load content
    url(r'^load/nosql/names', views.load_datamodels_and_nosqls_names, name='load_data_models_and_nosqls_names'),
    url(r'^delete/nosql/data', views.delete_all_data, name='delete_all_data'),
    url(r'^load/nosql/dbengine', views.load_all_nosql_basic, name='load_all_nosql_basic'),
    url(r'^load/github/data', views.load_github_data_for_all_nosql, name='load_all_github_data'),
    url(r'^load/drivers/github/data', views.load_drivers_for_all_nosql, name='load_drivers_for_all_nosql'),
    url(r'^load/descriptions/data', views.load_descriptions_for_all_nosql, name='load_all_descriptions'),
    url(r'^load/stackshare/data', views.get_all_stackshare_votes, name='load_stackshare_votes'),
    url(r'^load/stackoverflow/data', views.get_all_stackoverflow_followers_and_questions, name='load_stackoverflow'),
    url(r'^load/form', views.search_results, name='search_form'),
    url(r'^output/form', views.output_form, name='output_form'),
    url(r'^load/comments', views.load_comments, name='load_comments'),

]

nosql_engine/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('nosql.urls', namespace='nosql'))
]

nosql/forms.py
from django import forms

class SearchForm(forms.Form):
    name = forms.CharField(required=False)
    min_rank = forms.IntegerField(required=False, label="Minimum Rank")
    max_rank = forms.IntegerField(required=False, label="Maximum Rank")

nosql/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect

from elasticsearch_dsl import Search, Q

# Models
from .models import DataModel, Nosql, License, ProgrammingLanguage, Link, Comment

# Forms
from .forms import SearchForm

# Crawlers
from .libs.webcrawlers.db_engine_crawlers import db_engine_main
from .libs.webcrawlers.github_crawler import github_crawler_main
from .libs.webcrawlers.stackshare_crawlers import stackshare_main
from .libs.webcrawlers.stackoverflow_crawlers import stackoverflow_main
from .libs.webcrawlers.google_crawlers import custom_search_engine_crawler
from .libs.data_processing.clean_data import google_cleaner

from .libs.utils import wikipedia_table
from .libs.utils import db_engine_table

from .libs.paginator import custom_paginator

from .libs.data_processing import nosql_data_manager, google_manager, stackoverflow_manager, official_website_manager
from .libs.data_processing import link_rank

from .libs.sentiment_classifier.performance_classifier import PerformanceClassifier
import time


############## Options for admin #####################

def load_datamodels(request, datamodels_names):
    for name in datamodels_names:
        DataModel.objects.get_or_create(name=name)

def load_nosqls(request, data):
    for datamodel_name, nosqls in data.items():
        datamodel = DataModel.objects.get(name=datamodel_name)
        for nosql in nosqls:
            url = nosql['info_url']
            name = nosql['name']
            Nosql.objects.get_or_create(name=name,
                                        data_url=url,
                                        datamodel=datamodel)


def load_nosql_basic_info_from_dbengine(request, id):
    nosql = Nosql.objects.get(id=id)
    basic_info = db_engine_table.get_main_info_from_source(nosql.data_url)

    url = nosql_data_manager.get_url(basic_info)
    developer = nosql_data_manager.get_developer(basic_info)
    initial_release = nosql_data_manager.get_initial_release(basic_info)
    current_release = nosql_data_manager.get_current_release(basic_info)
    license = nosql_data_manager.get_license(basic_info)
    languages = nosql_data_manager.get_languages(basic_info)
    data_types = nosql_data_manager.get_data_types(basic_info)
    systems = nosql_data_manager.get_systems(basic_info)
    impl_language = nosql_data_manager.get_implementation_language(basic_info)

    if url: nosql.official_website = url
    if developer: nosql.developer = developer
    if initial_release: nosql.initial_release = initial_release
    if current_release: nosql.current_release = current_release
    if data_types: nosql.typing = data_types
    if systems: nosql.operating_systems = systems
    if impl_language: nosql.implementation_language = impl_language

    if license:
        license.nosql = nosql
        license.save()
    if languages:
        for lang in languages:
            lang.nosql = nosql
            lang.save()
    nosql.save()
    print("Created nosql: %s, url: %s, developer: %s, systems: %s" %(nosql.name, nosql.official_website, nosql.developer, nosql.operating_systems))


def load_datamodels_and_nosqls_names(request):
    crawler = db_engine_main.DBEngineCrawler()
    data = crawler.get_nosqls_databases()
    load_datamodels(request, data.keys())
    load_nosqls(request, data)
    return redirect('nosql:nosql_list')

def load_all_nosql_basic(request):
    nosqls = Nosql.objects.all()
    for nosql in nosqls:
        load_nosql_basic_info_from_dbengine(request, nosql.id)
    return redirect('nosql:nosql_list')


# ************ Descriptions ******************
def load_descriptions(request, id):
    nosql = Nosql.objects.get(id=id)
    stack_description = stackoverflow_manager.load_description_from_stackoverflow(nosql.slug)
    official_description = official_website_manager.get_official_description(nosql.official_website)
    if stack_description is not None:
        nosql.stack_description = stack_description
    if official_description is not None:
        nosql.official_description = official_description
    nosql.save()

def load_descriptions_for_all_nosql(request):
    nosqls = Nosql.objects.all()
    for nosql in nosqls:
        load_descriptions(request, nosql.id)
    return redirect('nosql:nosql_list')

# ************* Github *******************
def load_repos_for_languages(id):
    nosql = Nosql.objects.get(id=id)
    required_drivers = ['c', 'java', 'perl', 'php', 'python', 'ruby', 'javascript']
    main_drivers = ProgrammingLanguage.objects.filter(slug__in=required_drivers, nosql=nosql)
    print("---> Main drivers: %s" %(main_drivers))
    for driver in main_drivers:
        if driver.amount_repos == 0:
            count_repo = github_crawler_main.get_count_language(nosql.slug, driver.slug)
            print("Count for the repo {%s}: %d" %(driver.name, count_repo))
            driver.amount_repos = count_repo
            driver.save()
        print("---> Driver nosql: %s, Driver name: %s, Driver count: %s" %(nosql.name, driver.name, driver.amount_repos))

def load_github_data_for_all_nosql(request):
    nosqls = Nosql.objects.all()
    for nosql in nosqls:
        try:
            amount = github_crawler_main.get_count_repos(nosql.slug)
            print("Amount of: %s -> %d" %(nosql.name, amount))
            nosql.amount_repos = amount
            nosql.save()
        except:
            time.sleep(80)
            continue
    return redirect('nosql:nosql_list')

def load_drivers_for_all_nosql(request):
    nosqls = Nosql.objects.all()
    for nosql in nosqls:
        try:
            load_repos_for_languages(nosql.id)
        except:
            time.sleep(80)
            continue
    return redirect('nosql:nosql_list')



def load_all_technologies_repos(request, id):
    nosql = Nosql.objects.get(id=id)
    technologies = github_crawler_main.get_count_for_all_languages(nosql.slug)
    print(technologies)
    amount = github_crawler_main.get_count_repos(nosql.slug)
    nosql.amount_repos = amount
    nosql.save()
    percentages = dict()
    total = nosql.amount_repos
    for key, values in technologies.items():
        name = key.lower()
        percentages[name] = (values * 100)/total
    print(percentages)
    return percentages

# **********************************************

def delete_all_data(request):
    # First delete all
    License.objects.all().delete()
    ProgrammingLanguage.objects.all().delete()
    Nosql.objects.all().delete()
    DataModel.objects.all().delete()
    return redirect('nosql:nosql_list')


# ************** Stackshare ***********************
def get_stackshare_followers(slug):
    stackshare_votes = 0
    stackshare = stackshare_main.StackshareCrawler(slug)
    if stackshare:
        stackshare_info = stackshare.get_attributes()
        if stackshare_info:
            if stackshare_info['Votes']:
               stackshare_votes = stackshare_info['Votes']
    return stackshare_votes

def get_all_stackshare_votes(request):
    nosqls = Nosql.objects.all()
    for nosql in nosqls:
        try:
            votes = get_stackshare_followers(nosql.slug)
            nosql.stackshare_votes = votes
            nosql.save()
        except:
            print("---Exception getting the info for: %s" %(nosql.slug))
            continue
    return redirect('nosql:nosql_list')

# *************** Stackoverflow *************************
def get_all_stackoverflow_followers_and_questions(request):
    nosqls = Nosql.objects.all()
    for nosql in nosqls:
         try:
            followers, questions = stackoverflow_main.get_followers(nosql.slug)
            nosql.stackoverflow_followers = int(followers)
            nosql.amount_stackoverflow_questions = int(questions)
            nosql.save()
            print("%s followers: %s, questions: %s" %(nosql.slug, nosql.stackoverflow_followers, nosql.amount_stackoverflow_questions))
         except Exception as e:
            print("# Error: %s" %(e))
            continue
    return redirect('nosql:nosql_list')


def get_stackoverflow_links(id):
    nosql = Nosql.objects.get(id=id)
    crawler = stackoverflow_main.StackoverflowScrapper(nosql.slug)
    stack_links = crawler.get_links()
    if stack_links:
        url_ranker = link_rank.UrlRank()
        for link in stack_links:
            try:
                rank = url_ranker.get_rank_of_link(link['url'])
                link_obj, created = Link.objects.get_or_create(title=link['title'], url=link['url'], nosql=nosql, number_backlinks=int(rank))
                print("Link {%s}: %d" %(link_obj.title, link_obj.number_backlinks))
                time.sleep(14)
            except Exception as e:
                print("# Error: %s" %(e))
                continue
    else:
        return None

# *************** Google ********************************
def load_comments(request):
    nosql_list = Nosql.objects.all()
    save_comments(nosql_list)
    return render(redirect('nosql:nosql_list'))



def save_comments(nosql_list):
    classifier = PerformanceClassifier()
    for nosql in nosql_list:
        actual_comments = Comment.objects.filter(nosql=nosql)
        if len(actual_comments) == 0:
            try:
                comments = google_manager.search_phrase(nosql.slug)
                for comment in comments:
                    body = comment['description']
                    label, prob = classifier.classify(body)
                    positive = (label == 1)
                    comment, created = Comment.objects.get_or_create(url=comment['url'],
                                                                     body=comment['description'],
                                                                     nosql=nosql,
                                                                     positive=positive,

nosql/templates/nosql_engine/nosql/detail.html
{% extends "nosql_engine/base.html" %}
{% load static %}

{% block title %}
    {% if datamodel %}{{ datamodel.name }}{% else %}Nosqls{% endif %}
{% endblock %}

{% block content %}
    <div>
        <h1>{{ nosql.name }}</h1>
        <h2><a href="{{ nosql.datamodel.get_absolute_url }}">{{ datamodel.name }}</a></h2>
        <p>{{ nosql.data_url }}</p>
        <h3>Stored info</h3>
        <ul>
            <li>Official website: {{ nosql.official_website }}</li>
            <li>Developer : {{ nosql.developer }}</li>
            <li>Initial release: {{ nosql.initial_release }}</li>
            <li>Current release: {{ nosql.current_release }}</li>
            <li>License: {{ license.name }} ({{ license_type }})</li>
            <li>Implementation language: {{ nosql.implementation_language }}</li>
            <li>Data Types: {{ nosql.typing }}</li>
            <li>Supported Programming Languages:
                {% for l in languages %}
                    <p> {{ l.name }} {{ l.amount_repos }}</p>
                {% endfor %}
            </li>
            <li>Operating Systems: {{ nosql.operating_systems }}</li>
        </ul>
    </div>
    {% if wiki_table %}
    <div>
        <ul>
            {% for attribute, value in wiki_table.items %}
            <li>{{ attribute }} : {{ value }}</li>
            {% endfor %}
        </ul>
    </div>
    {% else %}
        <h3>Without Wikipedia Table</h3>
    {% endif %}

    {% if links %}
    <div>
        <ul>
            {% for link in links %}
            <li><a href="{{ link.url }}">{{ link.title }}</a>: <span>{{ link.number_backlinks }}</span></li>
            {% endfor %}
        </ul>
    </div>
    {% else %}
        <h3>Without Links</h3>
    {% endif %}


    <div>
         {{ summary }}
    </div>

     {% if comments %}
    <div>
        {% for comment in comments %}
        <div>
            <span>Positive: {{ comment.positive }} probability: {{ comment.probability }}%</span>
            <hr>
            <p>{{ comment.body }}</p>
        </div>
        {% endfor %}

    </div>
    {% else %}
        <h3>Without Links</h3>
    {% endif %}
{% endblock %}

nosql/templates/nosql_engine/nosql/list.html
{% extends "nosql_engine/base.html" %}
{% load static %}

{% block title %}
    {% if datamodel %}{{ datamodel.name }}{% else %}Nosqls{% endif %}
{% endblock %}

{% block content %}
    <h2>Search:</h2>
        <form action="{% url 'nosql:search_form' %}" method="post">
            {% csrf_token %}
            <label for="name">Nosql name:</label>
            <input type="text" name="name" id="name"/>
            <label for="min_rank">Min.No stars:</label>
            <input type="number" name="min_rank" id="min_rank"/>
             <label for="max_rank">Max. No stars:</label>
            <input type="number" name="max_rank" id="max_rank" />

            {% for data_model in datamodels %}

               <div class="col-md-4">
                 <input type="checkbox" id="{{ data_model.slug }}" name="datamodel" value="{{ data_model.name }}" class="filled-in chk-col-blue">
                 <label for="{{ data_model.slug }}">{{ data_model.name }}</label>
               </div>

            {% endfor %}
            {% for driver in languages %}
                <div class="col-md-4">
                <input type="checkbox" id="{{ driver }}" name="driver" value="{{ driver }}" class="filled-in chk-col-blue">
                <label for="{{ driver }}">{{ driver }}</label>
              </div>
            {% endfor %}
            {% for license in licenses %}
              <div class="col-md-4">
                <input type="checkbox" id="{{ license }}" name="license" value="{{ license }}" class="filled-in chk-col-blue">
                <label for="{{ license }}">{{ license|title }}</label>
              </div>
            {% endfor %}
          </div>
            <input type="submit" value="Search" />
        </form>
    {% if datamodel_aggs %}
    <h2>Aggregations</h2>
    <ul>
        {% for agg in datamodel_aggs %}
            <li>
                <a href="{{ agg.url }}">{{ agg.name }}</a> ({{ agg.doc_count }})
            </li>
        {% endfor %}
    </ul>
    {% endif %}



    <div>
        <h3>Datamodels</h3>
        <ul>
            <li>
                <a href="{% url "nosql:nosql_list" %}">All</a>
            </li>
            {% for d in datamodels %}
                <li>
                    <a href="{{ d.get_absolute_url }}">{{ d.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>

    <div>
        <h1>{% if datamodel %}{{ datamodel.name }}{% else %}Nosqls{% endif %}</h1>
        {% if nosqls %}
            {% for nosql in nosqls %}
            <div class="item">
                <a href="{{ nosql.local_website }}">{{ forloop.counter }}.- Rank:{{ nosql.rank }} {{ nosql.name }} Datamodel: {{ nosql.datamodel }} - Stackshare votes: {{ nosql.stackshare_votes }} - Stack followers: {{ nosql.stackoverflow_followers }} - Questions: {{ nosql.amount_stackoverflow_questions }}</a>
                {{ nosql.stack_description }}
                <hr>

            </div>
            {% endfor %}
        {% else %}
            No results found. Please try another search term.
        {% endif %}
    </div>


<div class="pagination">
{% for pg in pages %}
   <li class="active"><a href="?page={{ pg }}">{{ pg }}</a></li>

          {% endfor %}
</div>


{% endblock %}